### ISSUE TITLE
Auth Frontend

### ISSUE THREAD

**Issue by Aras14HD** [sk4rd/jari#22]
# OIDC
- auth.html - "Sign in with Google" button (redirect to /auth/google/start)
- settings.html - delete user button and radio title, description and add button (DELETE /auth/user, PUT /{username})
# Links
- [Sign in with Google button guide](https://developers.google.com/identity/gsi/web/guides/display-button)

**Comment by nikderechte** [comment]
> # OIDC
> 
>     * auth.html - "Sign in with Google" button (redirect to /auth/google/start)                                  //ist auf login.html erstellt
> 
>     * settings.html - delete user button and radio title, description and add button (DELETE /auth/user, PUT /{username})
> 
> 
> # Links
> 
>     * [Sign in with Google button guide](https://developers.google.com/identity/gsi/web/guides/display-button)
